### ISSUE TITLE
Data Coverage

### ISSUE THREAD

**Issue by SeisPider** [HimaTibetMap/HimaTibetMap#17]
Thank u for your sharing. I have a suggestion about data presentation.

Could you please add an overview map of data coverage and distribution?

**Comment by cossatot** [comment]
Hi, you can see this by clicking on the geojson file (github displays it automatically): https://github.com/HimaTibetMap/HimaTibetMap/blob/master/geojson/HimaTibetMap.geojson

**Comment by SeisPider** [comment]
ok, I know it and thank u sincerely for your respond.

在2017-06-07 20:22:53，xiaoX2013301140017@whu.edu.cn写道：

Hi, you can see this by clicking on the geojson file (github displays it automatically): https://github.com/HimaTibetMap/HimaTibetMap/blob/master/geojson/HimaTibetMap.geojson
